
[theme]
name="termplate"
description="a nice termplate description"
author="who?"
version="1.0.0"
git="https://github.com/your/repo"
depends=["waybar"]
config="theme.conf"

[script]
cleanup="./cleanup"

[kill]
exclude_bars=["eww"]
exclude_wallpapers=["swww"]
